/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_geosrv_Proj */

#ifndef _Included_cc_geosrv_Proj
#define _Included_cc_geosrv_Proj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_geosrv_Proj
 * Method:    open
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jlong JNICALL Java_cc_geosrv_Proj_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cc_geosrv_Proj
 * Method:    projLonLat
 * Signature: (DD[D)Z
 */
JNIEXPORT void JNICALL Java_cc_geosrv_Proj_proj
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdoubleArray);

/*
 * Class:     cc_geosrv_Proj
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_geosrv_Proj_free
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
